### ISSUE TITLE
Better error message for using super when not using an object method

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#212]
```
Object.create({}, {
  foo: {
    get: function(){
      return super.foo;
    }
  }
})
```

errors with

```
repl: 'super' outside of function or class (4:13)
  2 |   foo: {
  3 |     get: function(){
> 4 |       return super.foo;
    |              ^
  5 |     }
  6 |   }
  7 | })
```

since it needs to be a `get() {}`

We should make a better error message for this?

cc @jasonkarns @kovensky

**Comment by Kovensky** [comment]
Would be better to say "method or class constructor", as only those have a `[[HomeObject]]` (and thus access to `super`).

Right now it _is_ inside a function, it's just a "free-standing" closure that happens to be assigned to an object.

Worse, if it did try to just use the object where the closure is defined, its `[[HomeObject]]` would be the property descriptor itself 😄

**Comment by hzoo** [comment]
Yeah "method or class constructor" sounds good to me?

https://github.com/babel/babylon/blob/01e984fd0f21bb284943a508d2acc7c458aab13e/src/parser/expression.js#L379-L392

Also interesting is `allowSuperOutsideMethod` - we should update the readme since it says TODO https://github.com/babel/babylon/blob/master/README.md#options - not sure why you would want that

**Comment by Kovensky** [comment]
`allowSuperOutsideMethod` would probably only make sense if `super` was dynamic and would work like `Object.getPrototypeOf(Object.getPrototypeOf(this))`.

**Comment by jasonkarns** [comment]
No suggestions on the error message, but I'll say that from my perspective, I'm not sure that `method or class constructor` would have been any more illuminating than the current message. It's absolutely precise, but also not all that helpful to the majority of users. (if they're like me)

It would probably take more work (since the error message would need to be contextual) but if going for the most helpful message, one could print exactly what needs changed to make it valid. (At least for function expressions used within property descriptors.)

**Comment by rajzshkr** [comment]
I can work on this issue. Seems to be good for first contribution.

**Comment by nicolo-ribaudo** [comment]
@rajzshkr Go ahead!
