### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by SerkanSipahi** [babel/babylon#220]
Im trying to generate with `babel-template` an es6 ImportDeclaration but it doest work.

```js
import { transform, template, types } from 'babel-core';
```

```js
let compileImportTemplate = template(`
    import { IMPORT_NAME } from SOURCE;
`);
compileImportTemplate({
    IMPORT_NAME: types.identifier("foo"),
    SOURCE: types.stringLiteral("./a/b/c"),
});
```
```error
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
```
### Babylon/Babel Configuration
```js
{
  "parserOpts": { 
        "sourceType": "module"
   }
}
```

This works, es5 require
```js
let compileImportTemplate = template(`
    var IMPORT_NAME = require(SOURCE).IMPORT_NAME;
`);
compileImportTemplate({
    IMPORT_NAME: types.identifier("foo"),
    SOURCE: types.stringLiteral("./a/b/c"),
});
```

This is also works:
```js
let ImportDeclaration = transform(`import {${importName}} from "${source}"`).ast.program.body;
```

| software         | version
| ---------------- | -------
| babel-core          |  6.18.2
| node             | v5.1.0
| npm              | 3.3.12
| Operating System | OS X El Capitan 10.11.6

**Comment by loganfsmyth** [comment]
`.babelrc` options apply to the file content being transformed by Babel itself. The error you are seeing is from

```
let compileImportTemplate = template(`
    import { IMPORT_NAME } from SOURCE;
`);
```

you need to do

```
let compileImportTemplate = template(`
    import { IMPORT_NAME } from SOURCE;
`, {sourceType: 'module'});
```

except that won't work because `SOURCE` is not valid ES6 syntax. The module path needs to be a string to parse properly, so you can't use it like this with `template`.

**Comment by SerkanSipahi** [comment]
@loganfsmyth thank you. You are right. Its not valid es6. I wrapped it with single quotes.

This works fine:
```js
let compiledTemplate = template(`
    import { IMPORT_NAME } from 'SOURCE';
`, { sourceType: 'module' });

let res = compiledTemplate({
    IMPORT_NAME : t.identifier('foo'),
    SOURCE: .stringLiteral("./a/b/c"),
});

```

**Comment by loganfsmyth** [comment]
Keep in mind my last point though:

> The module path needs to be a string to parse properly, so you can't use it like this with template.

because now `'SOURCE'` is just a string containing the word `SOURCE`, not a replaceable identifier that `babel-templates` knows how to handle with the `types.stringLiteral("./a/b/c"),` replacement. You'll have to set the source string manually after you get the AST back from your template function.

**Comment by SerkanSipahi** [comment]
@loganfsmyth right

```js
let compiledTemplate = template(`
    import { IMPORT_NAME } from 'SOURCE';
`, { sourceType: 'module' });

let res = compiledTemplate({
    IMPORT_NAME : types.identifier('foo'),
});
res.source.value = "./a/b/c";
```
