### ISSUE TITLE
JSX Attributes are not parsed/escaped properly w/ babel+babylon

### ISSUE THREAD

**Issue by djcoin** [babel/babylon#271]
Hi! JSX attribute parsing does not produce the expected result to me and is escaped too early (before being handled aas a regular var by react). Attributes like title or value are not properly rendered as a result.

### Input Code

```js
var src = "<div title='café'></div>";

var result = require("babel-core").transform(src, { 
  plugins: ["syntax-jsx"]
  // or: plugins: ["transform-react-jsx"]
})

console.log(result.code)
```

### Expected Behavior

```html
<div title="café"></div>;
```
### Current Behavior

```html
<div title="caf\xE9"></div>;
```

### Details

Relevant and stripped down AST produced by babylon:

```js
"openingElement": {
  "type": "JSXOpeningElement",
  "attributes": [
    { "type": "JSXAttribute"
      "name": {
	"type": "JSXIdentifier",
	"name": "title"
      },
      "value": {
	"type": "StringLiteral",
	"extra": null,
	"value": "café"
      }
    }]
}
```

The value being a StringLiteral with no extra, it is handled in babel-generator (lib/generators/types.js) as a StringLiteral and fully escaped in jsesc (a regular var assignment - eg: var x = 'café' - has a node.extra element : {value: .., rawValue: ...} that prevents it from being escaped inside jsesc).

I'm not sure what the fix is but I think we should treat JSX attributes as regular assignment.
A simple fix would be to remove  the "node.extra = null;" in jsxParseAttributeValue (it does work, verified).
But I guess it is here for a reason?

I can make a pull request if you see the proper way to fix it.
Thank you!

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.14.1 (but tested w/ the most recent one)

**Comment by djcoin** [comment]
Maybe it depends on the configuration stack, if the JSX is transformed in another JSX but not in a call to React.createElement, it will have this behavior, see: 

https://jsfiddle.net/gszkduk2/7/

**Comment by djcoin** [comment]
Does anyone have any feedback on this? Thanks!

**Comment by danez** [comment]
I'm with you, that this is inconsistent in the AST, but it seems it was done because of
https://github.com/babel/babylon/commit/ffee5615e4d6db9db789f634272dbd2f77b0ec4c
https://github.com/babel/babel/issues/2114

But both are rather old and we can try to remove the `node.extra = null;` line here, and see if the cases mentioned in the other ticket work now or if we find a better solution.

I will remove it as a test and see if the babel tests work.

**Comment by danez** [comment]
I think this a edge case, as usually jsx is transformed to js and there the escaped text is valid. and will never show up in the DOM like this. Not sure actually what to about this.

**Comment by djcoin** [comment]
Well the think is 

```js
var x = "foo", bar = <div title={x} />;
```

and 

```js
var bar = <div title="foo" />
```

Should behave the same. Reactjs is waiting for normal js variable.

**Comment by danez** [comment]
It is not the same, in the first example the StringLiteral is escaped according to js specs. In the second example "foo" would be need to escaped according to xhtml specs. That is the major difference and babel seems to always assume the output should be js encoded, as we usually (in 99%) transpile jsx to js.

But if you do jsx-to-jsx then this behaviour is wrong.

Also for example this is correct:

```js
<div pattern="\w"></div>;
```

but going through babel without any transform results in

```js
<div pattern="\\w"></div>;
```

which is not the same. We might be able to detect if the parent is jsx in babel-generator and based on that not use `jsesc` but something else that creates a valid xhtml escaped-valid string literal from the input value.

//cc @mathiasbynens because I mentioned jsesc and maybe you have an idea.

**Comment by djcoin** [comment]
> In the second example "foo" would be need to escaped according to xhtml specs

Would it? This is react's task I would say.
