### ISSUE TITLE
[7.0] Remove classConstructorCall plugin

### ISSUE THREAD

**Issue by danez** [babel/babylon#286]
This plugin is deprecated and needs to be removed for 7.0. It was already removed from the documentation a while ago. Make sure to remove:
 * Tests
 * Program code that is related to it.

As a starting point this can help:
https://github.com/babel/babylon/search?utf8=%E2%9C%93&q=classConstructorCall

**Comment by hzoo** [comment]
And to be clear the proposal for this is dropped: http://babeljs.io/docs/plugins/syntax-class-constructor-call

Can use your previous PR as a reference (https://github.com/babel/babylon/pull/98/commits) although it's not exactly the same since that was just removing the hasPlugin check and this issue is about removing the plugin + code.
