### ISSUE TITLE
How to extend Babylon features?

### ISSUE THREAD

**Issue by Volune** [babel/babylon#354]
I want to add an experimental feature to Babel/Babylon.

I was expecting to add that feature through a plugin, or patch the Parser, But I can't find a way to do it, it seems everything is hidden behind the `parse` function.

I would like to avoid forking Babylon+Babel。 Am I missing something?

**Comment by danez** [comment]
I'm sorry, but we currently do not allow to extend babylon. 

The reason is that as soon as we do this we would have to be really careful with breaking changes, as right now even some simple fixes involve breaking the internal API. If we would make it public we would break external plugins with every release.

So for now the only way is to fork babylon and make your changes in the fork.

**Comment by Volune** [comment]
I'll fork then, thanks.
