### ISSUE TITLE
How to avoid hardcoded plugin lists?

### ISSUE THREAD

**Issue by eventualbuddha** [babel/babylon#396]
Any projects that use bablyon to do source code transformation or analysis typically want to operate on any code that bablyon is capable of parsing. Unfortunately, that means enabling all flags and plugins in every place that babylon is used. Inevitably this list of flags and plugins falls behind eventually.

What do you propose for dealing with this problem? Should we allow passing a `parseTarget` option, or something, that would take `es2015`, `es2017`, `stable`, `latest`, etc? We had `*` as a plugin option that enabled all plugins, but [that was removed](https://github.com/babel/babylon/pull/245) because of the potential for conflicting plugins.

**Comment by loganfsmyth** [comment]
Currently the concern is all for Stage < 4 functionality. Take decorators for instance, we currently have the old decorators spec exposed as the decorators plugin, but we'd like to add the new spec. Since we want people to actually upgrade to Babel 7, we can't replace the old decorators with the new one as a breaking change, so instead we're likely going to add a second decorators plugin for the new spec language.

If we expose `*` that will cause a conflict between the plugins.

One option that comes to mind is that we could publish a `babel-babylon` package that would automatically enable your plugins based on your `.babelrc`. Now sure how people feel for that.

**Comment by hzoo** [comment]
Maybe what we can do instead is make `*` different or make another option that basically just checks the current list of plugins and then does a console.warn to tell you if there's an updated version to use instead
