### ISSUE TITLE
[proposal] merge babel with eslint

### ISSUE THREAD

**Issue by lx93uv** [babel/babylon#564]
`eslint` use `espree` parser, built on top of `acorn.js`.
`babel` use `babylon` parser, built on top of `acorn.js`.

I think, it's will be great if  `eslint` and `babel` become a single project - it will be perfect suite for `js` developing.

**Comment by hzoo** [comment]
Hey @lx93uv! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by peey** [comment]
I think ESLint and Babel are very different projects. AFAIK ESLint basically enforces good habits and checks your code style, and Babel basically transforms your future (and experimental) JavaScript to a functionally equivalent old JavaScript. One can be used without the other (though a lot of people do use them both)

I think this is also why the parsing differs, since it serves different needs. If all this is correct then it'd be really difficult to merge the two projects. 

What's your use case here? Did you encounter any problems using Babel and ESLint together? Is it because of efficiency (having to install and configure them separately)?

**Comment by ljharb** [comment]
Personally, I think more smaller projects is much better than one large, bloated, multipurpose project.

Separately, eslint is useful even when not using babel, and not everyone using babel uses eslint.

**Comment by lx93uv** [comment]
Thanks for your replies.

As I understand, technically both `eslint` and `babel` developers can unite efforts to contributing of `acorn`. IMHO, if several projects use the same piece of software, they should unify it's interface and contribute to it together together.

From developer point of view, work can be represented as stream from
* compiling from `es6/7/etc` to `es5` according to `babel-env`
* linting, static analysis (`eslint`)
* minifying (`babili`)
so, all tasks can be implemented as `acorn` plugins, isn't it?

And, @ljharb, management of big "bloated" project is not a problem with proper people.

**Comment by ljharb** [comment]
@lx93uv that having talented people can largely mitigate the inherent flaws in having a large project does not alter that it is inherently flawed.
