### ISSUE TITLE
How to create a custom babylon plugin?

### ISSUE THREAD

**Issue by janryWang** [babel/babylon#678]
I see the plugins are now coupled in this directory, https://github.com/babel/babylon/tree/master/src/plugins,
I want to create a plugin with a separate repository

**Comment by hzoo** [comment]
Hey @janryWang! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by janryWang** [comment]
@hzoo Because i want to develop a private unofficial babylon plugin that is dedicated to helping me parse the code.But I did not find babylon had this ability.

**Comment by danez** [comment]
We do not support external plugins in babylon. We already have a lot of work in maintaining all the internal plugins and the project itself and if we would make the current plugin api available to the public we would need to be way more careful when changing things in babylon. Right now most changes would be breaking changes if the plugin API would be public, as we very often need to change stuff around and we would not be able to guarantee a stable API or make every single release a major one.

**Comment by janryWang** [comment]
Thanks @danez , But I still hope that babylon has external scalability. Can you consider supporting this ability in the future?

**Comment by nicolo-ribaudo** [comment]
[As suggested in the readme](https://github.com/babel/babylon/blob/master/README.md#will-babylon-support-a-plugin-system), you can fork Babylon and implement your own plugin (if you need examples, you can check the files in `src/plugins`).

It is very unlikely that we will ever support a plugin system, since lots of bugfix and new features need the internal methods (that would be used by external plugin[As suggested in the readme](https://github.com/babel/babylon/blob/master/README.md#will-babylon-support-a-plugin-system), you can fork Babylon and implement your own plugin (if you need examples, you can check the files in `src/plugins`).

It is very unlikely that we will ever support a plugin system, since lots of bugfix and new features need the internal methods (that would be exposed to external plugins) to be changed: there would be breaking changes in almost every release. 😅

**Comment by hzoo** [comment]
https://github.com/babel/babylon#faq

We should write a better guide on how to do it but yeah
