### ISSUE TITLE
Split export extensions into 2

### ISSUE THREAD

**Issue by hzoo** [babel/babylon#706]
So this is more of a refactor

exportExtensions:
Proposal 1: `export v from "mod"`
Proposal 2: `export * as ns from "mod"`

Like in https://github.com/babel/babel/pull/6080 except for the babylon plugin.

`exportDefault`?
`exportNamespace`?

- Check contributing https://github.com/babel/babylon/blob/master/CONTRIBUTING.md#creating-a-new-plugin-spec-new

---

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [CONTRIBUTING.md](https://github.com/babel/babylon/blob/master/CONTRIBUTING.md)
- [ ] Split the plugins into 2
- [ ] fix all the test fixtures (may need 2 folders, pass the correct option down)

**Comment by rajikaimal** [comment]
Would like to work on this !

**Comment by swapnilraj** [comment]
Hi I would like to help with this.👍

**Comment by pudility** [comment]
I am not sure how far above my level this is, but I would like to give it a shot, just so I understand correctly, What this is trying to do is change something like this:
```js
export default () => {
    throw new Error('test');
};
```
Out:
```js
Error: test
    at exports.default
```
---
into something like this:
```js
let baz = () => {
    throw new Error('test');
};

export default baz;
```
Out:
```js
Error: test
    at baz
```

**Comment by existentialism** [comment]
@pudility sounds good, but do you mind if we check if @rajikaimal has made any progress first (just want to make sure they didn't make a bunch of effort on it)?

**Comment by pudility** [comment]
Definitely, how should we check?

**Comment by jridgewell** [comment]
Just see if he responds. If not by tomorrow, I'd say go for it.

**Comment by pudility** [comment]
Great! Will do.

**Comment by pudility** [comment]
Before I set up my babylon environment and test it more thoroughly, I would really appreciate it if someone would look over [my code](https://github.com/pudility/Export-Extensions) just to make sure that I am doing everything correctly. Thank you!

**Comment by existentialism** [comment]
@pudility just to be clear, this task is to split up the `exportExtensions` plugin inside of **Babylon** into `exportDefault` and `exportNamespace` since they are two separate proposals.

Check out the link to CONTRIBUTING in the original post by @hzoo for info on adding a new plugin. The Babel side was completed in https://github.com/babel/babel/pull/6080.

**Comment by pudility** [comment]
So the thing I made already exists, but what still needs to be made is something for exportNamespaces? For example, something like this:
```js
exports.hello = () => {}
```

**Comment by hzoo** [comment]
@pudility this task is a refactor; there is no behavior to implement - we need to split the logic. 
https://github.com/babel/babylon/blob/65bea96544561c68bdf84fa9f85bc7afdd3535c8/src/parser/statement.js#L1266-L1274 so that `this.hasPlugin("exportExtensions")` is split

**Comment by hzoo** [comment]
exportextensions used to be 1 proposal and now its 2.

export-default-from https://github.com/babel/proposals/issues/17
export-ns-from https://github.com/babel/proposals/issues/16

they are indepdent and at different stages so we should split them up. you just need to change `this.hasPlugin` to use 2 new strings, update the readme/docs, and update the folders/tests

**Comment by pudility** [comment]
Ok, thank you so much for explaining, I now get it. I will give it a shot, but I am not quite sure if I will be able to do it fully.

**Comment by pudility** [comment]
@hzoo I think this may be a bit above my current skill level. I am going to keep looking through the code, but I don't think that I will be able to solve this issue. Thanks again for the help.

**Comment by jridgewell** [comment]
It should be as simple as using two separate plugin strings. Right now, we have one string (`"exportExtensions"`) that enables two separate features. We want to remove that string, and instead replace it with (`"exportDefault"` and `"exportNamespace"`).

**Comment by pudility** [comment]
Oh, Thats simpler than I thought. I just added that, I will update the docs and then create a PR.

**Comment by pudility** [comment]
So I have modified the code to now look like this:
```js
  parseExport(node: N.Node): N.Node {
    // export * from '...'
    if (this.shouldParseExportStar()) {
      this.parseExportStar(node, (
        this.hasPlugin("exportDefault") ||
        this.hasPlugin("exportNamespace")
      ));
      if (node.type === "ExportAllDeclaration") return node;
    } else if (this.hasPlugin("exportDefault")) {
```
and I replace [export-expressions](https://github.com/babel/babylon/tree/master/test/fixtures/experimental/export-extensions) with `export-default` and `export-namespace`. I also changed the `options.json` file in both of them to use the plug in `"exportDefault"` and `"exportNamespace"` respectively. I think that I must have done something wrong here (probably when modifying `statement.js`) because when I run `yarn run test-only` I get three errors:
```python
  4223 passed
  3 failed
  112 skipped

  index › experimental/export default/default

  /Users/zoe/Developer/babylon/split-export/babylon/test/helpers/runFixtureTests.js:21

   20:               name + "/" + task.actual.filename + ": " + err.message;
   21:             t.fail(message);
   22:           }

  experimental/export-default/default/actual.js: Unexpected token, expected { (1:7)
```
plus two almost identical errors:
2. `experimental/export-namespace/ns/actual.js: Unexpected token (1:9)`
3.  `experimental/export-default/default-type-without-flow/actual.js: Unexpected token, expected { (1:7)`

---
Thank you all so much for helping me create my first real contribution to Babylon, I really like getting to learn the process for all of this stuff.
